# Generated by Django 2.0.3 on 2018-03-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_deneme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
